name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-web-site:${{ github.run_number }}

  updating_deploymet_file:
    runs-on: ubuntu-latest
    needs: build  # Waits for the Docker image build to complete

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}  # A PAT with repo push access

      - name: Update tag in deployment
        run: |
          echo "GitHub Run Number: ${{ github.run_number }}"
          cp -f deployment.yaml manifests/
          sed -i "s/replaceImageTag/${{ github.run_number }}/g" portfolio-web-site/manifests/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "akash.jaiswal36@gmail.com"
          git config --global user.name "akashjaiswal36"
          git add portfolio-web-site/manifests/deployment.yaml
          git commit -m "Update deployment to tag ${{ github.run_number }}" || echo "No changes to commit"
          git push
